name: Check PR base ref

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Check PR base ref
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo Add other actions to build,
        cat README.md
        echo "Env:"
        env
        echo "Action:"
        cat "${GITHUB_EVENT_PATH}"
        yarn
        node ./check-pr-base.js
