name: Log on PR changes

on:
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo Add other actions to build,
        cat README.md
        echo "Env:"
        env
        echo "Action:"
        cat "${GITHUB_EVENT_PATH}"
        node ./check-pr-base.js
